### PR TITLE
Allows both dashes or underscores for v8flag word separator.

### PR DESCRIPTION
**Pull request by sttk**
In [Node.js API document](https://nodejs.org/api/cli.html#cli_v8_options), there is a description that:

> Note: V8 options allow words to be separated by both dashes (-) or underscores (_).
> For example, --stack-trace-limit is equivalent to --stack_trace_limit.

This pr is for supporting this.

### CODE REVIEW

**Comment by phated** [comment]
@sttk has node supported this since 0.10 or maybe it only supported underscores?

@tkellen is this something we want to support?

**Comment by sttk** [comment]
@phated Yes. v0.10 supports this specification. Following is the result I tried:

```sh
$ cat test.js
const s = 'hello';
console.log(s);
$ node -v
v0.10.48
$ node test.js
hello
$ node --use_strict test.js

/Users/sttk/test.js:1
(function (exports, require, module, __filename, __dirname) { const s = 'hello
                                                              ^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:945:3
$ node --use-strict test.js

/Users/sttk/test.js:1
(function (exports, require, module, __filename, __dirname) { const s = 'hello
                                                              ^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:945:3
$ # Execute with unsupported flag
$ node --use--strict test.js
Error: unrecognized flag --use--strict
Try --help for options
hello
$
```

**Comment by phated** [comment]
@sttk any idea why this is failing?

**Comment by sttk** [comment]
The reason of failing in this and other PRs is only timeout. In [my travis test](https://travis-ci.org/sttk/js-flagged-respawn/builds/314346840?utm_source=github_status&utm_medium=notification), those tests succeeded.

This timeout is caused in the same test case and it is the first test case using `child_process.exec`.
Since It simply executes  `./test/bin/respawner.js` which is used other test cases, I think that first `child_process.exec` spent a lot of time.

We may need to set timeout longer for this test case or on the whole.

**Comment by phated** [comment]
Cherry-picked as c787fb176904dd3880562da7dd620d210802b89e

**Pull request closed without merging**
