### PR TITLE
Force and forbid respawning

### PR DESCRIPTION
**Pull request by sttk**
This pr enables to forbid respawning with `--no-respawning` cli flag, and enables to respawn with specified node flags.

This pr will help to solve js-liftoff's [issue #89](https://github.com/js-cli/js-liftoff/pull/89), gulp-cli's [issue #109 comment](https://github.com/gulpjs/gulp-cli/issues/109#issuecomment-309250144), and issue #4.

### CODE REVIEW

**Comment by sttk** [comment]
I'm sorry but there is a problem that mocha return exit code 0 in spite of error. This cause is seemed to be in my test code. Please wait.

**Comment by sttk** [comment]
The cause of the problem above is original two test cases which execute `flaggedRespawn` so that respawn is needed.
I created the pr #9 for this problem, and rebased this pr on #6, #9 and #8 clearly.

**Comment by phated** [comment]
Cherry-picked and amended as 7ca348671e060f22bf541b59d78bc3ff9cc0a4d8 

@sttk this series of PRs have been amazing and I'm glad we're moving to a solution on this stuff. Thanks so much!!

**Comment by sttk** [comment]
Thank you for merging! I'm glad, too.

**Pull request closed without merging**
