### PR TITLE
Make sure that flags values are preserved

### PR DESCRIPTION
**Pull request by tusbar**
See https://github.com/gulpjs/gulp/issues/1564#issuecomment-197460151.

### CODE REVIEW

**Comment by tkellen** [comment]
Thanks for submitting this @tusbar! Just a heads up that I won't be able to review this until Monday.

**Comment by tusbar** [comment]
No problem :)

**Comment by tkellen** [comment]
This looks great @tusbar, thank you so much!

I've just added you as a collaborator both here and on NPM. Please feel free to cut a patch release. If you have any questions about how to do that, ask away!

**Comment by tusbar** [comment]
Ok, will do. I’ll still open PRs for all the changes I make.

**Comment by tkellen** [comment]
Sounds great, thanks @tusbar!

**Comment by tusbar** [comment]
@tkellen it’s all done:
- [0.3.2](https://www.npmjs.com/package/flagged-respawn) is published to npm
- I’ve [added a PR to liftoff](https://github.com/js-cli/js-liftoff/pull/65) that fixes a similar issue

**Pull request merged**
